name: Build and release

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-2022
    env:
      Solution_Name: SteamRecordingEnhanced
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Store artifacts
        uses: actions/upload-artifact@v6
        with:
          name: SteamRecordingEnhanced
          path: .\SteamRecordingEnhanced\bin\x64\Release\SteamRecordingEnhanced\*
          if-no-files-found: error
          retention-days: 1
  release:
    runs-on: windows-2022
    needs: build
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Download
        uses: actions/download-artifact@v7
        with:
          name: SteamRecordingEnhanced
          path: ./artifacts
      - name: Display structure of downloaded files
        run: ls -R ./artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        id: release
        with:
          fail_on_unmatched_files: true
          files: ./artifacts/latest.zip
      - name: Make repo.json
        run: |
          $url = '${{ fromJSON(steps.release.outputs.assets)[0].browser_download_url }}'
          $iconUrl = 'https://raw.githubusercontent.com/${{ github.repository }}/refs/tags/${{ github.ref_name }}/icon/icon_128px.png'
          $inPath = './artifacts/SteamRecordingEnhanced.json'
          $outPath = './repo.json'
          $manifest = Get-Content -Raw $inPath | ConvertFrom-Json
          $manifest | Add-Member -MemberType NoteProperty -Name 'DownloadLinkInstall' -Value $url
          $manifest | Add-Member -MemberType NoteProperty -Name 'DownloadLinkUpdate' -Value $url
          $manifest | Add-Member -MemberType NoteProperty -Name 'IconUrl' -Value $iconUrl
          $manifest | Add-Member -MemberType NoteProperty -Name 'DownloadCount' -Value "0"
          ConvertTo-Json -InputObject @($manifest) | Set-Content -Path $outPath -Encoding UTF8
      - name: Print repo.json
        run: Get-Content $outPath